### PR TITLE
Make header smaller

### PR DESCRIPTION
**Pull request by ubergesundheit**
Just a suggestion on making the header smaller.

This pull request also removes the big header for the blog altogether

@sensebox/everyone please comment

smaller-header

### CODE REVIEW

**Comment by felixerdy** [comment]
On smaller devices (e.g. smartphones) not all content of the header is displayed. See following screenshot (iPhone 5)
bildschirmfoto 2017-05-15 um 14 31 50


The button is missing above
bildschirmfoto 2017-05-15 um 14 33 16

**Comment by ubergesundheit** [comment]
Yeah right. Maybe either the headline or the text below should be hidden on mobile? Or maybe smaller in order to show the buttons?

**Comment by mpfeil** [comment]
I would go for a smaller header and text below font size.
Maybe its also possible to hide the heading **senseBox in Medien und Presse** so we can use the space for showing content and/or using it for the header.

**Comment by ubergesundheit** [comment]
Here are some screenshots

0 0 0 0 4000 de materials-320x568-cropped
0 0 0 0 4000 de press-320x568-cropped
0 0 0 0 4000 de background-320x568-cropped
0 0 0 0 4000 de osem-320x568-cropped
0 0 0 0 4000 de products-320x568-cropped
0 0 0 0 4000 de awards-320x568-cropped
0 0 0 0 4000-320x568-cropped
0 0 0 0 4000 en materials-320x568-cropped
0 0 0 0 4000 en press-320x568-cropped
0 0 0 0 4000 en background-320x568-cropped
0 0 0 0 4000 en osem-320x568-cropped
0 0 0 0 4000 en products-320x568-cropped
0 0 0 0 4000 en awards-320x568-cropped
0 0 0 0 4000 en-320x568-cropped

**Pull request closed without merging**
