### PR TITLE
create ampel, kaminfeuer, lauschangriff and luegendetektor project pages

### PR DESCRIPTION
**Pull request by bkari02**
- Created 4 project pages
- Author of Kaminfeuer was set to unknown 
- Author of Ampel was set to Björn

### CODE REVIEW

**Comment by bkari02** [comment]
Ampelschaltung project can be used for Blockly and Arduino, is there a way to use both ide tags for it? by default this doesn't really work out fine as you can see in the preview.

**Comment by bkari02** [comment]
> Ampelschaltung project can be used for Blockly and Arduino, is there a way to use both ide tags for it? by default this doesn't really work out fine as you can see in the preview.

@mariopesch

**Comment by mariopesch** [comment]
> > Ampelschaltung project can be used for Blockly and Arduino, is there a way to use both ide tags for it? by default this doesn't really work out fine as you can see in the preview.
> 
> @mariopesch

You should create on project for each programming environment otherwise the filtering makes no sense

**Comment by bkari02** [comment]
> > > Ampelschaltung project can be used for Blockly and Arduino, is there a way to use both ide tags for it? by default this doesn't really work out fine as you can see in the preview.
> > 
> > 
> > @mariopesch
> 
> @bkari02 You should create on project for each programming environment otherwise the filtering makes no sense

@mariopesch 
Created duplicate of Ampelschaltung so the filter function is able to handle it now. Any other issues to be solved?

**Comment by bkari02** [comment]
> Das Kapitel für die LED sollte Schrittweise aufgebaut werden mit mehr Erläuterungen. Nicht einfach nur Aufbau und dann den Code vorgeben

I assume that you talk about the "Ampelschaltung" projects? 
The two projects for that topic were revised.

**Pull request merged**
